### ISSUE TITLE
Letter /g

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#10]
I think there is a problem with points in the outline of the letter /g. In the attached image I highlighted the two points that do not match (regular and bold).

![Common Serif g](https://user-images.githubusercontent.com/68413054/233825129-1a741a19-db8b-450e-80d1-4ce9a6fc21b6.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
