### ISSUE TITLE
Letter /S

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#11]
I think there is a problem with points in the outline of the letter /S. In the attached image I highlighted the points (bold).

![Common Serif Bold S](https://user-images.githubusercontent.com/68413054/233825868-ff07db1d-5aec-4f0d-addb-74769b70f6e0.jpg)

See Common Serif Medium letter /S:

![Common Serif Medium S](https://user-images.githubusercontent.com/68413054/233825872-52890b01-3d24-4c70-8e85-f23428758fa6.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
