### ISSUE TITLE
Letter /n.sc

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#12]
I think there is a problem with points in the outline of the letter /n.sc. See Common Serif Medium:

![Common Serif Medium n_sc](https://user-images.githubusercontent.com/68413054/233826290-367df755-f15e-4599-ad55-c6222151c697.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
