### ISSUE TITLE
Letter /Q.u

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#13]
I think there is a problem with points in the outline of the letter /Q.u. See Common Serif Medium:

![Common Serif Medium Q_u](https://user-images.githubusercontent.com/68413054/233826493-2136b8b8-5d1c-428f-9e40-afb609e38d68.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
