### ISSUE TITLE
/s_t and /germandbls.ss03

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#14]
I think there is a problem with points in the outline of /s_t and /germandbls.sso3. See Common Serif Medium:

![Common Serif Medium s_t](https://user-images.githubusercontent.com/68413054/233826772-31e0a2ee-a3d4-4fad-885c-12b2da05b9d5.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
