### ISSUE TITLE
Letter /t.sc

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#15]
I think there is a problem with points in the outline of the letter /t.sc. See Common Serif Medium:

![Common Serif Medium t_sc](https://user-images.githubusercontent.com/68413054/233826891-a5c31deb-c789-40a1-9db8-b93cc5c9fa27.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
