### ISSUE TITLE
Letter /Udieresis.alt

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#16]
I think there is a problem with points in the outline of the letter /Udieresis.alt. See Common Serif Medium:

![Common Serif Medium Udieresis_alt](https://user-images.githubusercontent.com/68413054/233826960-6a0e02a0-1737-4044-aead-ed9a22c4bac4.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the note! The problem is solved in v.1.006.
