### ISSUE TITLE
Problems with italic

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#19]
Please, verify these letters in Italic/BoldItalic:
* /q points not matching
* /s different starting point
* /T different starting point
* /Z different starting point
* /z points not matching
* /q.sc points not matching

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the notes. Fixing all the mistakes that come from the Libertinus Serif font is a very long job. And any flag pointing out specific inconsistencies is welcome.

**Comment by StefanPeev** [comment]
@m-casanova Italic masters are upgraded to v.1.006 in which the problems of #19 are solved. Thank you again.
