### ISSUE TITLE
Possible problems in Regular/Bold version 1.010

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#21]
I think there are possible problems with these:
  * /p.sc /r.sc -> points not matching (top left inner angle)
  * /w.sc -> different shape compared to /W or /w
  * /iogonek -> points not matching
  * /tcaron /uni021B /uni1E71 -> points not matching
  * /longs /uni1E9B -> points not matching
  * /uni01D5 /uni01D9 -> points not matching
  * /uni026D -> points not matching
  * /uni027A -> points not matching
  * /uni037C -> points not matching
  * /uni0475 /uni0477 -> points not matching
  * /uni04A1 -> points not matching
  * /uni1D4F -> points not matching
  * /uni1D51 -> points not matching
  * /uni1E1F -> points not matching
  * /uni1E65 /uni1E69 -> points not matching
  * /uni2115 /uni2124 -> different shapes Regular/Bold
  * /uni2C6C -> points not matching
  * /ntilde.sc /nacute.sc ncaron.sc -> points not matching
  * /tcaron.sc /uni021B.sc -> points not matching
  * /germandbls.ss03 -> points not matching

**Comment by StefanPeev** [comment]
Solved.
