### ISSUE TITLE
Possible problems in Italic/BoldItalic version 1.006

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#22]
I think there are possible problems with these:
* /percent -> points not matching
* /quotesingle -> points not matching
* /period -> points not matching
* /colon -> points not matching
* /dieresis -> points not matching
* /iogonek -> points not matching
* /uring -> points not matching
* /uhungarumlaut -> points not matching
* /uogonek -> points not matching
* /zacute -> points not matching
* /zdotaccent -> points not matching
* /zcaron -> points not matching
* /uni035E -> points not matching
* /Zeta -> points not matching
* /Tau -> points not matching
* /uni0408 -> points not matching
* /uni0423 -> points not matching
* /uni1E6A /uni1E6C /uni1E6E /uni1E70 -> points not matching
* /uni1E73 /uni1E75 /uni1E77 /uni1E79 /uni1E7B -> points not matching
* /quotereversed /uni201F -> points not matching
* /onedotenleader /twodotenleader /ellipsis -> points not matching
* /uniA789 /uniA78B -> points not matching
* /uni1D106 /uni1D107
* /parentleft.sc /parentright.sc -> points not matching
* /odieresis.sc -> points not matching (see dieresis)
* /s_t -> points not matching
* /uni043F.ital

**Comment by StefanPeev** [comment]
@m-casanova Solved. Thank you!
