### ISSUE TITLE
Possible problems (1.008 Italic / 1.013 Regular)

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#23]
Sorry to annoy again.

Italic/BoldItalic version 1.008:
* /percent : different starting point
* /quotesingle : different starting point
* /A (and derived like /Agrave) : different starting point
* /b : different starting point
* /d (and derived like /dcaron /dcroat) : different starting point
* /uni00B3 : points not matching (bottom right)
* /gamma : different starting point
* /uni1E79 : different starting point + verify use of /u
* /uni1E7B : verify use of /u
* /uni1D106 /uni1D107 : different starting points (circles and bigger rectangle)
* /k.sc : different starting points (both shapes)
* /uni0454 : different starting points
* /uni1E9E : verify use of /S /S
* /germandbls.ss03 : different /s shapes Italic/BoldItalic

Regular/Bold version 1.013:
* /uni0287 /uni1E97 : verify use of /t (different starting point)
* /uni1E94 : verify use of /Z
* /uni2096 : different starting point

**Comment by StefanPeev** [comment]
@m-casanova Solved!
