### ISSUE TITLE
Possible problems (1.009 Italic / 1.014 Regular)

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#24]
Italic/BoldItalic version 1.009:
* /percent : different starting point (lower zero)
* /q : points not matching (external shape)
* /mu : points not matching
* /Eng /eng : points not matching
* /Zdotaccent /Zcaron /uni01C4 : verify use of Z
* /uni0266 : different shape Italic/BoldItalic
* /uni0279 : different shape
* /uni03D0 : different shape (not sure)
* /uni0413 : points not matching
* /uni042A : points not matching
* /uni042C (and /uni042B) : different starting point (up left)
* /uni1E19 /uni1E1B : verify use of /e
* /perthousand /uni2031 : points not matching
* /uni2079 /uni2089 : points not matching
* /uni2083 : points not matching
* /uni2090 : different shape
* /uni0414.loclBGR : points not matching
* /f_l : different shape
* /w.sc : different central serifs

Regular/Bold version 1.014:
* /uni25c9 : dot not centered (Bold)
* /c.inferior /k.inferior : points not matching
* /uni2646 : points not matching

**Comment by StefanPeev** [comment]
@m-casanova Solved. Thank you!
