### ISSUE TITLE
Kerning pair for swash ampersand and capital A

### ISSUE THREAD

**Issue by StefanPeev** [StefanPeev/Common-Serif#25]
@apparebit [#536](https://github.com/alerque/libertinus/issues/536)
Q&A is not an uncommon abbreviation and, when typeset in Libertinus Serif, can benefit from that typeface's handsome swash ampersand alternate letter form. Alas, the standard kerning between the ampersand and capital A is so terrible that even I noticed. Adding a kerning pair would be a fantastic improvement to the font.

The screen shot below shows Q&A in Libertinus Serif Regular with the regular ampersand, then with the alternate ampersand and no kerning correction, and then with my quick and dirty manual kerning correction.

![Q_ampersand_A_kerning](https://user-images.githubusercontent.com/12949369/235184045-011d7e94-eee7-4ce3-8c74-59da781746b6.png)

To reproduce, just type "Q&A" in a new document in your favorite text editor with reasonable typography and replace the default ampersand with the alternate. For example, in macOS's TextEdit, open the font menu pop up in the document's toolbar and select "Show Fonts..." That brings up the Fonts mini window. Open the "..." menu pop up and select "Typography..." That brings up the Typography mini window. Under "Alternative Stylistic Sets," select "Swash '&'." (Sorry, not one of Apple's finer UI designs.)

**Comment by StefanPeev** [comment]
@apparebit The issue #25 is solved in v.1.036N/v.1.033I. Please, check and comment.

**Comment by apparebit** [comment]
@StefanPeev, very nice! Do you share changes upstream? I am somewhat pessimistic about the likelihood of the ACM switching to Common-Serif. See [acmart](https://github.com/borisveytsman/acmart).

**Comment by StefanPeev** [comment]
@apparebit My goal is not to make anyone change their font selection preferences. The project is gradually finding its place and is undoubtedly getting better and better both in terms of technical execution and the completeness of the glyph system.
