### ISSUE TITLE
Floral hearts ☙ ❦ ❧

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#30]
@StefanPeev Do you plan to modify /uni2619 and /uni2767?
See [this glif file](https://github.com/StefanPeev/Common-Serif/files/11399613/uni2766_variation.txt) for a possible contour for /uni2766 (and /uni2619 and /uni2767 when mirrored/rotated); it's based on /uni2767 from [Crimson Text](https://github.com/skosch/Crimson) (Google Fonts, OFL) with a slight variation

![uni2766](https://user-images.githubusercontent.com/68413054/236271028-400dae3b-d6d7-4a34-931a-ca8d3c2c3c50.jpg)

**Comment by StefanPeev** [comment]
I used another sources for /uni2619, /uni2766, /uni2767. Here is the result for the v.1.023

![CommonSerif_1200x625_03](https://user-images.githubusercontent.com/12949369/236303644-c6f16f3d-6373-4c30-9eeb-9e14308d8b55.jpg)

**Comment by StefanPeev** [comment]
@m-casanova The source files of version 1.023 are uploaded.
