### ISSUE TITLE
Weight 450

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#31]
Please consider adding an instance for weight = 450 in release (Thick or News, not sure of the correct name).
I think it would be useful for readability at a slightly reduced size

**Comment by StefanPeev** [comment]
@m-casanova weight 460 can be named Book. Is it OK?

**Comment by m-casanova** [comment]
There seems to be no unanimous consensus on this matter (e.g. [Regular vs Book](https://typedrawers.com/discussion/4766/regular-vs-book) on TypeDrawers).
But I think there is no problem to use 'Book' as name for a weight between 400 and 500.

**Comment by StefanPeev** [comment]
@m-casanova Weight 450 with the name News is included in v.1.024.
