### ISSUE TITLE
/uni2016 in formulas

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#33]
/bar and /uni2016 are not consistent (e.g. [Vertical bar](https://en.wikipedia.org/wiki/Vertical_bar) on Wikipedia)

/bar and /uni2016 in STIX Two Math vs. Libertinus/Common Serif:

![uni2016](https://user-images.githubusercontent.com/68413054/236660460-49da159a-2618-4b67-83c7-d69250159001.jpg)

I think that /uni2016 should use the same height, vertical position and spacing of /bar
Also /uni2016 has different height in Regular and Bold

Italic: Libertinus/Common Serif uses a slanted version of /bar and /uni2016, while STIX Two Text uses vertical bars

![uni2016_b](https://user-images.githubusercontent.com/68413054/236661732-ea2d925e-37e4-461e-9a5b-f73502f28dde.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the suggestions. I'll check the issue for the next version.

**Comment by StefanPeev** [comment]
/bar and /uni2016 in v.1.025 of Common Serif.

![CommonSerif_1200x625_07](https://user-images.githubusercontent.com/12949369/236701530-bc69ec35-bdfd-4b84-bec8-444774250c52.jpg)

**Comment by waldyrious** [comment]
I think @m-casanova was suggesting to lower `/uni2016` to the height of `/bar`, rather than raising `/bar` to `/uni2016`'s height. I'm no typography expert but the smaller-height bars do look better to me. Was it a deliberate choice to do the opposite change?

**Comment by m-casanova** [comment]
As @waldyrious said, it's better to lower /uni2016. The previous height of /bar is consistent with brackets.

![math bar](https://user-images.githubusercontent.com/68413054/236732685-62a999b6-4733-48d2-9306-9f7da0f91391.jpg)

**Comment by StefanPeev** [comment]
@m-casanova @waldyrious Please, check the latest version 1.026.

**Comment by m-casanova** [comment]
@StefanPeev  Thanks.
In BoldItalic v. 1.026 /bar and /uni2016 are higher.

![bar1](https://github.com/StefanPeev/Common-Serif/assets/68413054/d48a4a4b-0a0b-4263-abfe-3de3b024c942)

**Comment by StefanPeev** [comment]
@m-casanova Thanks, solved.
