### ISSUE TITLE
/space width

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#34]
I think /space should be narrower.

| Master  | Current width | 
|---|---|
| Regular | 250 |
|Bold | 250 |
|Italic | 340 |
|BoldItalic | 250 |

Example with /space width = 180 (Regular and Italic)

![regular - space 180](https://user-images.githubusercontent.com/68413054/236669334-bb064072-1056-4656-ab25-8ecb208023d8.jpg)

![italic - space 180](https://user-images.githubusercontent.com/68413054/236669382-e222fb95-2d25-4d62-8e41-ce93b9d16ec9.jpg)

Example with /space width = 200 (Bold and BoldItalic)

![bold - space 200](https://user-images.githubusercontent.com/68413054/236669399-9e54df26-ce3b-4fa2-b8e4-1f677eb5c260.jpg)

![bolditalic - space 200](https://user-images.githubusercontent.com/68413054/236669409-32c4347e-7c0a-4170-b204-9db46b88880a.jpg)

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the suggestions. I'll check the issue for the next version.

**Comment by StefanPeev** [comment]
@m-casanova Widht is set to 220.

**Comment by m-casanova** [comment]
/nbspace (= /uni00A0) should have the same width as /space (220)

**Comment by StefanPeev** [comment]
@m-casanova Both are set to 240 (/nbspace/uni00A0).
