### ISSUE TITLE
Fractions

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#35]
I think numerators and denominators vertical positions should be consistent with fraction like /onehalf and /onequarter (and /fraction seems different too)

![frac](https://user-images.githubusercontent.com/68413054/236670695-29f79b2f-6b8d-4922-be02-82f9eb17ccc4.jpg)

Also some fractions seem inconsistent (e.g. different denominator positions in /onehalf and /onequarter in Bold)

**Comment by m-casanova** [comment]
Probably numerators and denominators should be added instead of using superscript and subscript numbers

**Comment by StefanPeev** [comment]
@m-casanova Thank you for the suggestions. I'll check the issue for the next version.

**Comment by StefanPeev** [comment]
@m-casanova In Regular:

![CommonSerif_1200x625_08](https://user-images.githubusercontent.com/12949369/236716607-24303d6d-5102-45a4-8a44-5a7b1afedda8.jpg)

**Comment by m-casanova** [comment]
@StefanPeev  I'm sorry. I was referring to fractions created with the opentype "frac" feature, which are inconsistent with built-in fractions (like /onehalf). Example in LibreOffice Writer:

![frac2](https://user-images.githubusercontent.com/68413054/236736798-8f45682f-4dd8-4678-952b-b9358b25698b.jpg)

"frac" feature uses superscript and  subscript to create fractions, but I think numerators and denominators should be added. And /fraction should be modified to reflect built-in fractions.

Also the vertical position of numbers in built-in fractions should be checked (e.g. "2" in /onehalf seems slightly higher than "4" in /onequarter; see "8" in ⅛ ⅜ ⅝ ⅞)

**Comment by StefanPeev** [comment]
@m-casanova New full functioning fraction feature is included in v.1.026.

**Comment by m-casanova** [comment]
@StefanPeev  Sorry to annoy you again.
In Italic (v. 1.026) numerators are like superscripts. Example with `/onesuperior` `/one.numr` `/onehalf` and overlapping `/one.numr` `/onehalf`

![frac3](https://github.com/StefanPeev/Common-Serif/assets/68413054/dd3e0347-7304-4d1b-bba1-ee612ed0438c)

Also previously width was fixed (tabular) for superscripts and subscripts; now it's variable (proportional) for superscripts, numerators and denominators, while it's fixed for subscripts (Italic and BoldItalic).
Personally I prefer fixed width numbers for tables, but I know that different fonts use different methods (e.g. _Libertinus_ and _Source Serif_ use fixed width, while _STIX Two Text_ uses variable width).

![frac4](https://github.com/StefanPeev/Common-Serif/assets/68413054/c01be867-06be-41c3-817c-90cc6e3c97a7)

**Comment by m-casanova** [comment]
Subscript numbers are not consistent with others subscripts

![frac](https://github.com/StefanPeev/Common-Serif/assets/68413054/1c1da530-1df9-4fd2-877e-3b5c77e14981)

Also sups, numr, dnom and subs height seems inconsistent

![frac](https://github.com/StefanPeev/Common-Serif/assets/68413054/e7615f1c-18bc-4072-93ea-ed5ae8ae78b5)

**Comment by StefanPeev** [comment]
Superscript glyphs are a little bit higher then nomerator glyphs and the subscript glyphs are a little bit lower then denominator glyps. Denominators lay on baseline.
Here is the picture for Normal style.

![CommonSerif_1200x625_10](https://github.com/StefanPeev/Common-Serif/assets/12949369/fcf33164-e6f8-4c30-be3c-b8eef617c880)
