### ISSUE TITLE
/c_t and /s_t

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#37]
Please verify /c_t shapes (Regular and Bold in particular)

![ct](https://user-images.githubusercontent.com/68413054/236688440-c0a89e2c-2e4b-4a60-ac23-3d93aff323cf.jpg)

Also /s_t shapes (t in Regular)

![st](https://user-images.githubusercontent.com/68413054/236688443-7bf46f19-bc36-48ac-902b-b51039872ea7.jpg)

Also I'm not sure about the spacing between the letters

**Comment by waldyrious** [comment]
What did you use to generate the diff images, @m-casanova?

**Comment by m-casanova** [comment]
@waldyrious LibreOffice Draw (converting texts in curves)

**Comment by StefanPeev** [comment]
@m-casanova @waldyrious Check v.1.026.
