### ISSUE TITLE
/B regular v. 1.027

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#38]
Regular v. 1.027: /B width = 0

Test with LibreOffice Writer:

![/B regular](https://github.com/StefanPeev/Common-Serif/assets/68413054/51d3b494-1019-4e59-811f-ed49775fe327)

**Comment by StefanPeev** [comment]
@m-casanova Thank you! It is my mistake. A solved the problem in v.1.028.
