### ISSUE TITLE
Improve apostrophe kerning 

### ISSUE THREAD

**Issue by amarakon** [StefanPeev/Common-Serif#41]
Libertinus Serif has had horrible apostrophe kerning for a very long time, and it still hasn’t been fixed. Could you try to fix it with this fork? In the following image, the distance between the apostrophe and the ‘s’ is way too far, and the distance between the ‘d’ and the apostrophe is also probably slightly too much.

![common-serif-1](https://github.com/StefanPeev/Common-Serif/assets/92645199/c5ea71d1-34fa-431f-becb-295b92a45857)

**Comment by StefanPeev** [comment]
@amarakon Thank you for your note. I'll rework the metrics and apostrophe kerning for the next release.

**Comment by StefanPeev** [comment]
@amarakon Samples for apostrophe kerning in Common Serif for the next version of the font.

![CommonSerif_1200x625_17](https://github.com/StefanPeev/Common-Serif/assets/12949369/453f837a-7f95-4373-9d44-49d7c689086f)
![CommonSerif_1200x625_18](https://github.com/StefanPeev/Common-Serif/assets/12949369/e257ff74-66c8-4bac-9f68-30caf6e37ae4)
![CommonSerif_1200x625_19](https://github.com/StefanPeev/Common-Serif/assets/12949369/4125d4d8-19f4-4220-b696-8a186c1e143e)

**Comment by amarakon** [comment]
Aside from the apostrophe being too close to the following 'E' in "L'Est", it looks good.
