### ISSUE TITLE
Add half brackets

### ISSUE THREAD

**Issue by amarakon** [StefanPeev/Common-Serif#42]
Can you add the half bracket Unicode characters? These are `U+2E22`, `U+2E23`, `U+2E24`, `U+2E25`, respectively. The name “half bracket” is misleading though because they do not actually have to be half the height of a regular bracket. Actually, it is preferable that they are less then half the height of a regular bracket, because otherwise they would look weird. The following image shows the half brackets of the EB Garamond typeface stacked on top of each other, next to regular brackets. I did not measure it, but it looks like each half bracket is about 30–40% of the height of a regular bracket.

![half-brackets-1](https://github.com/StefanPeev/Common-Serif/assets/92645199/29d97688-b940-4243-8477-096afdc675c6)

**Comment by StefanPeev** [comment]
@amarakon You mean ['TOP LEFT HALF BRACKET' (U+2E22)](https://www.fileformat.info/info/unicode/char/2e22/index.htm), ['TOP RIGHT HALF BRACKET' (U+2E23)](https://www.fileformat.info/info/unicode/char/2e23/index.htm), ['BOTTOM LEFT HALF BRACKET' (U+2E24)](https://www.fileformat.info/info/unicode/char/2e24/index.htm) and ['BOTTOM RIGHT HALF BRACKET' (U+2E25)](https://www.fileformat.info/info/unicode/char/2e25/index.htm). OK, I'll add them.

**Comment by StefanPeev** [comment]
Here is what I include in Common Serif compare to other fonts.

![CommonSerif_1200x625_16](https://github.com/StefanPeev/Common-Serif/assets/12949369/122b82c4-fc92-46d9-907b-a2a373624d0f)

**Comment by amarakon** [comment]
Can you make them shorter? If the half bracket is actually half the height of a regular bracket, it looks extremely weird in text.

**Comment by StefanPeev** [comment]
@amarakon I put a question on different forums about the case. According to Adam Twardoch the half brackets should touch or overlap slighly like in the Brill and Gentium (see the picture above). Can you give me example of use of half brackets?

**Comment by StefanPeev** [comment]
@amarakon Here is the information which I found on Wikipedia:

> **Quine corners ⌜⌝ and half brackets ⸤ ⸥ or ⸢ ⸣**
> 
> The Quine corners ⌜ and ⌝ have at least two uses in mathematical logic: either as quasi-quotation, a generalization of quotation marks, or to denote the Gödel number of the enclosed expression.
> 
> Half brackets are used in English to mark added text, such as in translations: "Bill saw ⸤her⸥".
> 
> In editions of papyrological texts, half brackets, ⸤ and ⸥ or ⸢ and ⸣, enclose text which is lacking in the papyrus due to damage, but can be restored by virtue of another source, such as an ancient quotation of the text transmitted by the papyrus.[43] For example, Callimachus Iambus 1.2 reads: ἐκ τῶν ὅκου βοῦν κολλύ⸤βου π⸥ιπρήσκουσιν. A hole in the papyrus has obliterated βου π, but these letters are supplied by an ancient commentary on the poem. Second intermittent sources can be between ⸢ and ⸣. Quine corners are sometimes used instead of half brackets.

**Comment by amarakon** [comment]
> I put a question on different forums about the case. According to Adam Twardoch the half brackets should touch or overlap slighly like in the Brill and Gentium (see the picture above).

Ultimately, it’s the designer’s (your) choice. But in my opinion, they look a lot better when they don’t touch or overlap. I don’t have an explanation for it, it just looks better that way in my eyes. Perhaps you could make a character variant that users could enable if they wanted to.
