### ISSUE TITLE
Italic variant doesn't report as installed

### ISSUE THREAD

**Issue by waldyrious** [StefanPeev/Common-Serif#43]
I downloaded the latest 1.027 release and manually installed the fonts in my computer. However, whereas most of the `.otf` files behave as expected once installed, the italic variant continues to report as not installed, and if I try to install it again, duplicate files are added to my fonts directory. Perhaps there's some mistake in the italic variant's metadata?

Here's a [screencast](https://github.com/StefanPeev/Common-Serif/assets/478237/d409f734-1278-46e1-87c3-aaafc7e21d98) showcasing the issue.

For reference, I'm using Ubuntu 22.04.

**Comment by StefanPeev** [comment]
@waldyrious This is strange, because I haven't such problems on Windows 11. I'll think how to solve the problem.

**Comment by waldyrious** [comment]
Just tested with [v.1.028](https://github.com/StefanPeev/Common-Serif/releases/tag/CommonSerif_v.1.028) - the issue still occurs.

**Comment by tannenfreund87** [comment]
Can confirm. The italics also report as separate in some apps on my Windows 11 machine. Tested in Libreoffice, Wordpad and Firefox. The italics don't work in Libreoffice and Wordpad, but work as expected in Firefox.

**Comment by StefanPeev** [comment]
@waldyrious @tannenfreund87 Please, check the version 1.030.

**Comment by tannenfreund87** [comment]
> @waldyrious @tannenfreund87 Please, check the version 1.030.

Tested on Windows 10 in Word, Wordpad, LibreOffice and Firefox. Works! Thank you!
