### ISSUE TITLE
Uppercase B has zero width

### ISSUE THREAD

**Issue by waldyrious** [StefanPeev/Common-Serif#44]
Reproduction in LibreOffice Writer using the text `Ba Bb Bc`:

![image](https://github.com/StefanPeev/Common-Serif/assets/478237/fe5bd149-edb5-437b-91c0-b5bb32670cc8)

**Comment by StefanPeev** [comment]
@waldyrious This is a stupid mistake of mine. I fixed it for the next version. Thank you for the note.

**Comment by StefanPeev** [comment]
Fixed.

**Comment by waldyrious** [comment]
Oh, I see now this was a duplicate of #38!
