### ISSUE TITLE
Kerning of lowercase p is a little off

### ISSUE THREAD

**Issue by waldyrious** [StefanPeev/Common-Serif#45]
Note how the "p" is too close to the "i" in the word "episode" from [this paragraph](https://en.wikipedia.org/wiki/The_Telltale_Head#Production) of a random Wikipedia article:

**Libertinus Serif:**

![Screen Shot 2023-06-05 at 11 39 55](https://github.com/StefanPeev/Common-Serif/assets/478237/109f24a0-1744-4ed5-86f7-42706c8e1863)

**Common Serif**:

![Screen Shot 2023-06-05 at 11 39 44](https://github.com/StefanPeev/Common-Serif/assets/478237/fb35c184-1ccd-4c64-a9e2-72ca7ae7c524)

----

Detailed comparison:

![image](https://github.com/StefanPeev/Common-Serif/assets/478237/87df97da-3015-414e-bea0-624b9e0e884c)

**Comment by StefanPeev** [comment]
@waldyrious Thank you for the note, I'll check the issue.

**Comment by StefanPeev** [comment]
Fixed. Need to be checked.

**Comment by waldyrious** [comment]
Hmm... the kerning after the "p" seems better, but the kerning before it continues to be wider than Libertinus Serif, and IMO the latter works better.

**Common Serif before (v.1.027)**:
![common-serif](https://github.com/StefanPeev/Common-Serif/assets/478237/40902c32-fcb3-415c-98f9-46ade99b4639)

**Common Serif now (v.1.028)**:
![](https://user-images.githubusercontent.com/478237/243329439-fb35c184-1ccd-4c64-a9e2-72ca7ae7c524.png)

**Libertinus Serif**:
![](https://user-images.githubusercontent.com/478237/243329465-109f24a0-1744-4ed5-86f7-42706c8e1863.png)

(The difference in the images is clearer in 100% zoom.)

**Comment by StefanPeev** [comment]
@waldyrious In version 1.031 I made the horizontal metrics in "episode" to be the same as in Libertinus Serif.

**Comment by StefanPeev** [comment]
@waldyrious I close this issue because the problems are solved in v.1.033.
