### ISSUE TITLE
Incorrect glyph for ◕ (U+25D5)

### ISSUE THREAD

**Issue by StefanPeev** [StefanPeev/Common-Serif#46]
The same problem in Common Serif - see [link](https://github.com/alerque/libertinus/issues/538#issue-1716214724).

**Comment by waldyrious** [comment]
> The same problem in Common Serif

You mean Libertinus Serif, right? :)

**Comment by StefanPeev** [comment]
@waldyrious Probably. I did not open Libertinus Serif to look at it. I simply found the same problem in Common Serif. But as far as Common Serif is based on Libertinus Serif - obviously they both have one and the same problem.

**Comment by StefanPeev** [comment]
Fixed
