### ISSUE TITLE
Consider small design deviations from Libertinus Serif to make the font more self-consistent

### ISSUE THREAD

**Issue by waldyrious** [StefanPeev/Common-Serif#5]
Hey @StefanPeev, I would like to know if you'd be willing to consider revisiting some design decisions of Libertinus Serif in Common Serif.

For example, swapping the italics (and italics bold) capital "J" with its stylistic alternate (J.alt), so that the default is the one without the horizontal line, matching the style of the regular "J" in the other weights, as was proposed in https://github.com/alerque/libertinus/issues/98. Quick diagram based on the image from the associated PR https://github.com/alerque/libertinus/pull/138:

![image](https://user-images.githubusercontent.com/478237/215477882-206a7b36-42a8-43ec-b7a9-ea0539f0a10c.png)

... or changing the lowercase italics "p" to not have the hook to the left (that version could become `p.alt`). Here's a quick draft comparing to q and its italics version:

<img src="https://user-images.githubusercontent.com/478237/215477988-40836c75-d5ea-49a1-bca1-c756b6712639.png" width="450"/> 

Are small changes like these something you'd consider? I assume these two, in particular, may make it easier to produce continuous variations of the font, which IIUC is one of your goals.

**Comment by StefanPeev** [comment]
@waldyrious Thank you for the good ideas. I agree with you and I'll work in this direction. The truth is that a lot of changes must be made with the project, so that we to have a real consistence between the different styles and weights. It is why I decided to start the project under a new name. Actually it will be a new font - not exactly Libertinus Serif.

**Comment by StefanPeev** [comment]
@waldyrious In version 1.002 of Common Serif Italic **_J_** and **_p_** are with alternatives.
![JpFm5bJPQL](https://user-images.githubusercontent.com/12949369/216616576-81dab578-9593-4431-aade-62bfc723826f.png)
![3RigfL32hA](https://user-images.githubusercontent.com/12949369/216616625-61e77929-6072-4256-8c9e-b26216fa62de.png)

**Comment by waldyrious** [comment]
Awesome! Thanks for doing that ☺️

Since this issue is kind of open ended, how do you propose we deal with it? Should we close it or do you want to keep it open for additional changes?

**Comment by StefanPeev** [comment]
@waldyrious We can close it for now.
