### ISSUE TITLE
It's too terrible to watch interpolating 3 instances. (v.1.028)

### ISSUE THREAD

**Issue by MY1L** [StefanPeev/Common-Serif#51]
downloaded from https://github.com/StefanPeev/Common-Serif/releases/tag/CommonSerif_v.1.028

test text: I¡«»øĲƁȢɯɰʔʕʖʙʡʢʯϐϕϗϹϿѷӀ֏Ἲᾐ‡₠Ⅷ∞⌧④⑫

CommonSerif-Medium.otf:
![image](https://github.com/StefanPeev/Common-Serif/assets/58043328/8b192720-2a1d-4e1d-a514-e2ba4e7dc4ed)

CommonSerif-Bold.otf:
![image](https://github.com/StefanPeev/Common-Serif/assets/58043328/e4d315f3-e9a2-4a9d-ac55-691a478b4f54)

What happened?

**Comment by StefanPeev** [comment]
@MY1L Thank you for the remark. I'll solve the problems and I'll upload a new version of Common Serif.

**Comment by MY1L** [comment]
@StefanPeev btw,can variable font be added? (like “CommonSerif-VF.ttf”)

**Comment by StefanPeev** [comment]
@MY1L Yes, variable font can be added but it make sense to add variable font when all problems with the glyph contours are solved.

**Comment by StefanPeev** [comment]
@MY1L Please, check the version 1.030. I hope the problems are solved there.

**Comment by MY1L** [comment]
still unsolved😑
CommonSerif-Medium.otf Version 1.031:
![image](https://github.com/StefanPeev/Common-Serif/assets/58043328/81a6e8f7-78a3-4a7a-a87a-e92a0a77561d)
n
itilde
imacron
ibreve
iogonek
kgreenlandic
eng
uni01D0

and https://github.com/StefanPeev/Common-Serif/issues/53

and 232 glyphs are blank:
uni03FC
…
uniFE2F

and these glyphs are not used:
uni0305.100
uni0305.1000
uni0305.1050
uni0305.1100
uni0305.1150
uni0305.1200
uni0305.1250
uni0305.1300
uni0305.1350
uni0305.1450
uni0305.150
uni0305.1600
uni0305.200
uni0305.250
uni0305.300
uni0305.350
uni0305.400
uni0305.450
uni0305.50
uni0305.500
uni0305.550
uni0305.600
uni0305.650
uni0305.700
uni0305.750
uni0305.800
uni0305.850
uni0305.900
uni0305.950
uni0332.100
uni0332.1000
uni0332.1050
uni0332.1100
uni0332.1150
uni0332.1200
uni0332.1250
uni0332.1300
uni0332.1350
uni0332.1450
uni0332.150
uni0332.1600
uni0332.200
uni0332.250
uni0332.300
uni0332.350
uni0332.400
uni0332.450
uni0332.50
uni0332.500
uni0332.550
uni0332.600
uni0332.650
uni0332.700
uni0332.750
uni0332.800
uni0332.850
uni0332.900
uni0332.950
caron.cap
uni0306.cyr
uni0306.cyrcap
uni03020301
uni03020300
uni03020309
uni03020303
uni03060300
uni03060301
uni03060303
uni03060309
uni03040300
uni03040301
uni03080300
uni03080301
uni03080304
uni0308030C
uni03070304
uni03040308
uni03030304
uni03030301
uni03030308
uni030C0307
uni03070301
eight.oldstyle

uni20C0 ← sans-Serif?

**Comment by StefanPeev** [comment]
@MY1L The blank glyphs are set for future glyph development. For the other cases I'll make a check.

**Comment by StefanPeev** [comment]
@MY1L Some of the "unused" glyphs are used as a structural elements in combining glyphs. For example O + uni03030308 = uni1E4E

**Comment by MY1L** [comment]
Yes, I know, I mean(v1.031, otf) these seems not used by OpenType feature, like `mark` `ccmp`…🤔

**Comment by StefanPeev** [comment]
@MY1L I close this issue because the problems are solved in v.1.033.

**Comment by MY1L** [comment]
@StefanPeev not all problems had been solved😓 or increases more problem,

test text: ɁɄɪɫɬɮʡΆΎҬᾍᾎ 

v.1.031:
![image](https://github.com/StefanPeev/Common-Serif/assets/58043328/1e806b71-15e2-48b0-b1ef-d73cb4c01ee5)

v.1.033:
![image](https://github.com/StefanPeev/Common-Serif/assets/58043328/2a8b3430-bc72-4045-bc2a-b2c956ea110b)

and ⃀(u20C0) still **Sans**-Serif.
