### ISSUE TITLE
Broken SemiBold capital letter I

### ISSUE THREAD

**Issue by juujuujj** [StefanPeev/Common-Serif#52]
Likely an interpolation error. Applies to accented variants. 1.028 release
![image](https://github.com/StefanPeev/Common-Serif/assets/92593550/72e5ef34-4ca3-4b3f-a1e4-dc050f95465e)

**Comment by StefanPeev** [comment]
@juujuujj Thank you for the notice.

**Comment by juujuujj** [comment]
ps this is a great project but I hate it when I see pesky bugs nibbling off of the quality of this

**Comment by StefanPeev** [comment]
@juujuujj Before the end of the year I will take in mind all bugs and issues about Common Serif.

**Comment by StefanPeev** [comment]
@juujuujj Please, check the v.1.030. I hope the problems are solved there.

**Comment by StefanPeev** [comment]
@juujuujj  I close this issue because the problems are solved in v.1.033.
