### ISSUE TITLE
Some problems in Regular (v. 1.031)

### ISSUE THREAD

**Issue by m-casanova** [StefanPeev/Common-Serif#53]
In regular v. 1.031 I think there are some problems with points in:
* /Aringacute
* /Euro.fitted
* /Iotatonos /Iotadieresis
* /exclamdown.sc /uni2E18
* /w.sc
* /uni0246
* /uni1D35
* /uni1F38 /uni1F39 /uni1F3B /uni1F3C /uni1F3D
* /uni1FD8 /uni1FD9 /uni1FDA /uni1FDB
* /uni201F
* /u1D106 and /u1D107

**Comment by StefanPeev** [comment]
@m-casanova @MY1L I close this issue because the problems are solved in v.1.033.
