### ISSUE TITLE
Missing ŏ in smallcaps

### ISSUE THREAD

**Issue by aronvandepol** [StefanPeev/Common-Serif#58]
**Describe the bug**
The letter "ŏ" does not appear in small caps as expected across various applications, including LaTeX and font analysis tools like FontDrop. Instead of transforming to match the small caps styling, the "ŏ" character remains in its standard, non-small-caps form. This inconsistency disrupts the uniformity of text that is intended to be displayed entirely in small caps.

**Steps to reproduce**

Use a font that includes the character "ŏ" in a text editor or a LaTeX document. Format a section of text to display in small caps, including the "ŏ" character within this section.
Additionally, you can confirm this by uploading the font to FontDrop to inspect the character's rendering in small caps.

Expected: The "ŏ" character, when included in a section of text formatted to display in small caps, should transform and display as small caps, maintaining consistency with the rest of the text.
Actual: The "ŏ" character remains in its standard form, not matching the small caps styling of the surrounding text. This behavior occurs across different platforms and applications, including but not limited to LaTeX and FontDrop.

**Screenshots / logs**
<img width="272" alt="Screenshot 2024-03-30 at 00 05 08" src="https://github.com/alerque/libertinus/assets/64252048/da17aa3e-7e52-47d5-b2fb-0a5e72bfb5de">

Additional context
The issue was initially observed while working with LaTeX documents but was confirmed to be a broader problem using FontDrop, suggesting that the issue lies with the font's handling of the "ŏ" character in small caps. This problem may affect any text where uniform small caps formatting is crucial, impacting the visual consistency of the document.

It seems this issue also goes for ŭ and ĕ. It seems to revert back to the standard lowercase set.

(also posted at https://github.com/alerque/libertinus/issues/552)

**Comment by StefanPeev** [comment]
@aronvandepol The small caps feature has not been implemented consistently and comprehensively in the project Common Serif. It will take some time before this feature is built in sufficiently comprehensively. But in the next project upgrade, I have taken your comments into consideration. I present an image of all current small caps at the moment.

![Screenshot 2024-03-31 063038](https://github.com/StefanPeev/Common-Serif/assets/12949369/cd64ac55-20d4-466b-b1ee-180a83c9fe61)

/parenleft.sc/parenright.sc/bracketleft.sc/bracketright.sc/braceleft.sc/braceright.sc/exclamdown.sc/questiondown.sc/guillemotleft.sc/guillemotright.sc/guilsinglleft.sc/guilsinglright.sc/hyphen.sc/a.sc/b.sc/c.sc/d.sc/e.sc/f.sc/g.sc/h.sc/i.sc/j.sc/k.sc/l.sc/m.sc/n.sc 
/o.sc/p.sc/q.sc/r.sc/s.sc/t.sc/u.sc/v.sc/w.sc/x.sc/y.sc/z.sc/agrave.sc/aacute.sc/acircumflex.sc/atilde.sc/adieresis.sc/aring.sc/abreve.sc/aogonek.sc/ae.sc/aeacute.sc/uni01E3.sc/cacute.sc/ccaron.sc/ccedilla.sc/egrave.sc/eacute.sc/ecircumflex.sc/ecaron.sc/edieresis.sc/ebreve.sc/eogonek.sc/dcroat.sc/eth.sc/dcaron.sc/gbreve.sc/igrave.sc/iacute.sc/icircumflex.sc/idieresis.sc/idotaccent.sc/ntilde.sc/ograve.sc/oacute.sc/ocircumflex.sc/otilde.sc/odieresis.sc/ohungarumlaut.sc/obreve.sc/oe.sc/oslash.sc/thorn.sc/ij.sc/lacute.sc/lslash.sc/lcaron.sc/nacute.sc/ncaron.sc/eng.sc/Eng.UCStyle.sc/q.sc.u/racute.sc/rcaron.sc/sacute.sc/scedilla.sc/scaron.sc/uni0219.sc/tcaron.sc/uni021B.sc/uni0163.sc/tbar.sc/uring.sc/uhungarumlaut.sc/ugrave.sc/uacute.sc/ucircumflex.sc/udieresis.sc/ubreve.sc/germandbls.sc/yacute.sc/ydieresis.sc/zacute.sc/zdotaccent.sc/zcaron.sc

**Comment by aronvandepol** [comment]
It makes me very excited to see! Thank you for picking up on this so fast (or showing me the in progress.) Is there any way I can properly credit you and the font in my dissertation? (hoping this will release before its finished)

**Comment by StefanPeev** [comment]
@aronvandepol The issue #58 is solved in v.1.036N/v.1.033I. Please, check and comment.

**Comment by aronvandepol** [comment]
@StefanPeev 

Perhaps I have accidentally checked wrong, but on my device, and using '[FontDrop](https://fontdrop.info/#/?darkmode=true)' - I see the Capital Ŏ added but not the lowercase ŏ.

<img width="221" alt="Screenshot 2024-05-19 at 02 24 11" src="https://github.com/StefanPeev/Common-Serif/assets/64252048/72df110d-fdb7-4aeb-bb8d-c9ec3d9c85d7">


Thank you for picking this up!

**Comment by StefanPeev** [comment]
@aronvandepol Check v.1.037N/v.1.034I, please. This is still not the final variant but must be a step toward solvation of the problems with .SC OpenType features.

**Comment by aronvandepol** [comment]
Last update fixed it! 👍
