### ISSUE TITLE
Retain RFNs in OFL.txt

### ISSUE THREAD

**Issue by davelab6** [StefanPeev/Common-Serif#60]
While you don't use the Reserved Font Names, IMHO those in https://github.com/alerque/libertinus/blob/master/OFL.txt should be retained in your OFL file (and copyright notices in the font files)

**Comment by StefanPeev** [comment]
@davelab6 I changed OFL file. Is this the right way of changing? https://github.com/StefanPeev/Common-Serif/blob/main/OFL.txt
