### ISSUE TITLE
`st` not set as historical ligature?

### ISSUE THREAD

**Issue by dwhieb** [StefanPeev/Common-Serif#61]
I'm using Common Serif as a web font, and by default it displays `st` with the historical ligature, like so:

![image](https://github.com/user-attachments/assets/c4e17ab6-02d7-41d5-a4e7-1284e74fc53e)

(That image was captured from the Common Serif demo at LocalFonts.eu.)

Common Serif seems to be treating `st` as a common ligature rather than a historical ligature. Because of this, the only way I can turn off the `st` ligature is by turning off _all_ ligatures, which is undesirable.

Note that the similar `ct` ligature does seem to be treated as a historical ligature. It is only activated when I opt into historical ligatures for the font, which is the expected behavior.

**Comment by StefanPeev** [comment]
@dwhieb Please, give me a like to your website.

**Comment by dwhieb** [comment]
https://nisinoon.net/grammar

I've currently disabled common ligatures, so the `st` ligature isn't showing. But if you inspect the `<body>` tag in your browser and disable the `font-variant-ligatures` rule, you'll see the `st` ligature appear.

Alternatively, you can see the problem by taking the following steps:

1. Go to the [Common Serif page on LocalFonts.eu](https://localfonts.eu/shop/non-latin-scripts/hebrew-script/common-serif/).
2. Scroll down to the area where you can input sample text and type `st ct` in the box.
3. You should see the ligature on `st` but not `ct`. If you then change the OpenType settings so that Standard Ligatures are not included, the `st` ligature disappears. Alternatively, if you choose Historical Ligatures, the ligatures appear on both `st` and `ct`.

**Comment by StefanPeev** [comment]
@dwhieb Thank you, Daniel. What will you say if I place /s /t in DLIG feature. I think that LIGA feature must look like this.

`feature liga {
sub f f i by f_f_i;
sub f f l by f_f_l;
sub f f by f_f;
sub f i by fi;
sub f l by fl;

} liga;`

In HLIG ligature I'll place only the long s ligatures, everything else will be in DLIG ligatures.

**Comment by dwhieb** [comment]
I think that makes sense. It seems like the `st` ligature should be in the same category as the `ct` ligature, wherever that is.

It might be worth noting that the Libertinus font placed both `ct` and `st` in the HLIG category though:

https://github.com/alerque/libertinus/blob/master/sources/features/dhlig.fea

**Comment by StefanPeev** [comment]
@dwhieb I do not see reason `st` and `ct` ligatures to be placed in HLIG - it is better to be part of DLIG.

**Comment by dwhieb** [comment]
That's fine by me! I defer to your expertise.

**Comment by dwhieb** [comment]
Awesome! That's a huge help! Thank you!
