### ISSUE TITLE
Should the "st" ligature be on by default?

### ISSUE THREAD

**Issue by Sunspark-007** [StefanPeev/Common-Serif#63]
Hi, I'm taking a look at the font here.. looks good.

One thing that jumped out at me immediately, the tall curly connected "st" ligature is the default setting and it's active in both libreoffice and an e-book reader app.

Taking a look at Linux Libertine, the curly "st" ligature exists in the list of characters, but it's not on by default. Libertinus Serif doesn't have this ligature at all.

**Common serif having it on, is that a bug or is it intentional?**

Image below is 28 point at 100% zoom in LibreOffice. First two are otf, third is ttf.

![image](https://github.com/user-attachments/assets/83bf18c3-8989-4efa-b477-e460e3cfc95f)

**Comment by StefanPeev** [comment]
@Sunspark-007 "st" is not longer ligature by default from v.1.038.
